# -*- coding: utf-8 -*-
"""onnx_conversion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gGiqcbY583FIhYxe6PVHG3JHPSMVaEYN
"""

def standalone_tflite_inference(
    model_path: str = "./nsfw_detector.tflite",
    test_images_dir: str = "./test_images",
    size: int = 384
):
    """
    Standalone TFLite inference without transformers library.
    Useful for deployment scenarios.

    Args:
        model_path: Path to the TFLite model
        test_images_dir: Directory containing test images
        size: Input size for the model (default: 384)
    """
    # ============================================================================
    # Standalone TFLite Inference (Without Transformers Library)
    # ============================================================================
    # This code shows how to use the TFLite model for inference without needing
    # the transformers library - useful for deployment scenarios
    # ============================================================================

    def preprocess_image_for_tflite(image_path, size=384):
        """
        Preprocess image for TFLite model inference.
        Replicates the transformers processor behavior.

        Args:
            image_path: Path to the image file
            size: Target size (default: 384 for this model)

        Returns:
            numpy array ready for TFLite inference
        """
        # Load and resize image
        img = Image.open(image_path).convert('RGB')
        img = img.resize((size, size), Image.BILINEAR)

        # Convert to numpy array and rescale to [0, 1]
        img_array = np.array(img).astype(np.float32) / 255.0

        # Normalize with mean and std (specific to this model)
        mean = np.array([0.5, 0.5, 0.5], dtype=np.float32)
        std = np.array([0.5, 0.5, 0.5], dtype=np.float32)
        img_array = (img_array - mean) / std

        # Convert from HWC (Height, Width, Channels) to CHW (Channels, Height, Width)
        img_array = np.transpose(img_array, (2, 0, 1))

        # Add batch dimension: (C, H, W) -> (1, C, H, W)
        img_array = np.expand_dims(img_array, axis=0).astype(np.float32)

        return img_array

    # Load model (try ai_edge_litert first, fallback to tensorflow)
    print("Loading TFLite model...")
    try:
        from ai_edge_litert.interpreter import Interpreter
        print("Using ai_edge_litert interpreter")
    except ImportError:
        try:
            from tensorflow.lite import Interpreter
            print("Using TensorFlow Lite interpreter")
        except ImportError:
            print("✗ Error: Neither ai_edge_litert nor tensorflow.lite available")
            print("  Install one of: pip install ai-edge-litert OR pip install tensorflow")
            return

    interpreter = Interpreter(model_path=model_path)
    interpreter.allocate_tensors()

    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    # Get model info
    print(f"✓ Model loaded: {model_path}")
    print(f"  Input name: {input_details[0]['name']}")
    print(f"  Input shape: {input_details[0]['shape']}")
    print(f"  Output name: {output_details[0]['name']}")
    print(f"  Output shape: {output_details[0]['shape']}")

    # Test on multiple images
    print("\n" + "=" * 80)
    print("Running Standalone TFLite Inference")
    print("=" * 80)

    if not os.path.exists(test_images_dir):
        print(f"✗ Test images directory not found: {test_images_dir}")
        return

    image_files = [f for f in os.listdir(test_images_dir)
                   if f.lower().endswith(('.jpg', '.jpeg', '.png'))]

    if not image_files:
        print(f"✗ No image files found in {test_images_dir}")
        return

    print(f"\n{'Image':<30} | {'Prediction':<10} | {'Confidence':>10} | Details")
    print("-" * 90)

    for img_file in image_files:
        img_path = os.path.join(test_images_dir, img_file)

        # Preprocess image
        pixel_values = preprocess_image_for_tflite(img_path, size=size)

        # Run TFLite inference
        interpreter.set_tensor(input_details[0]['index'], pixel_values)
        interpreter.invoke()
        output = interpreter.get_tensor(output_details[0]['index'])

        # Get logits
        logits = output[0]

        # Convert to probabilities (softmax)
        exp_logits = np.exp(logits - np.max(logits))
        probs = exp_logits / np.sum(exp_logits)

        # Get prediction
        pred_id = int(np.argmax(probs))
        labels = {0: "NSFW", 1: "SFW"}
        prediction = labels[pred_id]
        confidence = probs[pred_id]

        # Format details
        details = f"NSFW: {probs[0]:.2%} | SFW: {probs[1]:.2%}"

        print(f"{img_file:<30} | {prediction:<10} | {confidence:>9.2%} | {details}")

    print("\n" + "=" * 80)
    print("✓ Standalone TFLite inference completed successfully!")
    print("=" * 80)

standalone_tflite_inference(
        model_path="./nsfw_detector.tflite",
        test_images_dir="./test_images",
        size=384
    )















!apt-get install python3.10
!apt-get update -y
!update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
!update-alternatives --config python3
# select python version
!apt install python3-pip
!apt install python3.10-distutils
!python --version

!sudo apt-get -y update
!sudo apt-get -y install python3-pip
!sudo apt-get -y install python-is-python3
!wget https://github.com/PINTO0309/onnx2tf/releases/download/1.16.31/flatc.tar.gz \
  && tar -zxvf flatc.tar.gz \
  && sudo chmod +x flatc \
  && sudo mv flatc /usr/bin/
!pip install -U pip \
  && pip install tensorflow==2.19.0 \
  && pip install ai_edge_litert==1.2.0 \
  && pip install -U onnx==1.17.0 \
  && python -m pip install onnx_graphsurgeon \
        --index-url https://pypi.ngc.nvidia.com \
  && pip install -U onnxruntime==1.18.1 \
  && pip install -U onnxsim==0.4.33 \
  && pip install -U simple_onnx_processing_tools \
  && pip install -U onnx2tf \
  && pip install -U protobuf==3.20.3 \
  && pip install -U h5py==3.11.0 \
  && pip install -U psutil==5.9.5 \
  && pip install -U ml_dtypes==0.5.1 \
  && pip install -U tf-keras==2.19.0 \
  && pip install flatbuffers>=23.5.26

!onnx2tf -i model_q4f16.onnx



"""# NSFW_DETECTOR_MINI"""

import os
from transformers import AutoImageProcessor, AutoModelForImageClassification
from PIL import Image
import torch

# Load model and processor
processor = AutoImageProcessor.from_pretrained("viddexa/nsfw-detection-nano", use_fast=False)
model = AutoModelForImageClassification.from_pretrained("viddexa/nsfw-detection-nano")
model.eval()

# Get image files
image_files = [f for f in os.listdir() if f.lower().endswith(('.jpg', '.jpeg', '.png'))]

print(f"{'Image':<30} | {'Prediction':<10} | {'Confidence':>10} | Details")
print("-" * 90)

for img_file in image_files:
    img = Image.open(img_file).convert("RGB")

    with torch.no_grad():
        inputs = processor(images=img, return_tensors="pt")
        probs = torch.softmax(model(**inputs).logits, dim=-1)[0]

    pred_id = int(probs.argmax())
    label = model.config.id2label[pred_id]

    # Format all probabilities
    details = " | ".join([f"{model.config.id2label[i]}: {p:.2%}" for i, p in enumerate(probs)])

    print(f"{img_file:<30} | {label:<10} | {probs[pred_id]:>9.2%} | {details}")

"""## CONVERT TO ONNX"""

import torch
from transformers import AutoModelForImageClassification, AutoImageProcessor

model_name = "viddexa/nsfw-detection-nano"
model = AutoModelForImageClassification.from_pretrained(model_name)
processor = AutoImageProcessor.from_pretrained(model_name, use_fast=False)
model.eval()

input_size = processor.size.get('height', 224)
print(f"Using input size: {input_size}x{input_size}")

sample_inputs = torch.randn(1, 3, input_size, input_size)

# Use BytesIO to control serialization
from io import BytesIO
import onnx

output_path = 'nsfw_detector_nano.onnx'

# Export with explicit single-file control
f = BytesIO()
torch.onnx.export(
    model,
    sample_inputs,
    f,
    export_params=True,
    opset_version=14,
    do_constant_folding=True,
    input_names=['pixel_values'],
    output_names=['logits'],
    dynamic_axes={
        'pixel_values': {0: 'batch_size'},
        'logits': {0: 'batch_size'}
    }
)

# Write to file
with open(output_path, 'wb') as out_file:
    out_file.write(f.getvalue())

print(f"✓ Model exported as single file: {output_path}")
print(f"Model labels: {model.config.id2label}")

"""## Infer from ONNX"""

import os
import onnxruntime as ort
from PIL import Image
import numpy as np
from transformers import AutoImageProcessor, AutoModelForImageClassification

# Load the ONNX model
onnx_model_path = "nsfw_detector_nano.onnx"
session = ort.InferenceSession(onnx_model_path)

# Load the processor for image preprocessing
processor = AutoImageProcessor.from_pretrained("viddexa/nsfw-detection-nano", use_fast=False)

# Load original model just to get the label mapping
model = AutoModelForImageClassification.from_pretrained("viddexa/nsfw-detection-nano")
id2label = model.config.id2label

# Softmax function
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)

# Get image files
image_files = [f for f in os.listdir() if f.lower().endswith(('.jpg', '.jpeg', '.png'))]

print(f"{'Image':<30} | {'Prediction':<10} | {'Confidence':>10} | Details")
print("-" * 90)

for img_file in image_files:
    img = Image.open(img_file).convert("RGB")

    # Preprocess the image
    inputs = processor(images=img, return_tensors="np")
    pixel_values = inputs['pixel_values']

    # Run ONNX inference
    onnx_inputs = {session.get_inputs()[0].name: pixel_values}
    outputs = session.run(None, onnx_inputs)

    # Get logits and apply softmax
    logits = outputs[0]
    probs = softmax(logits)[0]

    pred_id = int(np.argmax(probs))
    label = id2label[pred_id]

    # Format all probabilities
    details = " | ".join([f"{id2label[i]}: {p:.2%}" for i, p in enumerate(probs)])

    print(f"{img_file:<30} | {label:<10} | {probs[pred_id]:>9.2%} | {details}")

import torch
from transformers import AutoImageProcessor, AutoModelForImageClassification
import numpy as np

model_name = "viddexa/nsfw-detection-mini"
model = AutoModelForImageClassification.from_pretrained(model_name)
processor = AutoImageProcessor.from_pretrained(model_name, use_fast=False)
model.eval()

input_size = processor.size.get('height', 224)
print(f"Using input size: {input_size}x{input_size}")

sample_inputs = torch.randn(1, 3, input_size, input_size)

output_path = 'nsfw_detector_mini.onnx'

# CRITICAL: Use dynamo=False to use the legacy (stable) exporter
torch.onnx.export(
    model,
    sample_inputs,
    output_path,
    export_params=True,
    opset_version=14,
    do_constant_folding=True,
    input_names=['pixel_values'],
    output_names=['logits'],
    dynamic_axes={
        'pixel_values': {0: 'batch_size'},
        'logits': {0: 'batch_size'}
    },
    dynamo=False  # Use legacy exporter - more stable for vision models
)

print(f"✓ Model exported: {output_path}")
print(f"Model labels: {model.config.id2label}")

# Validation
import onnxruntime as ort

session = ort.InferenceSession(output_path)

test_input = sample_inputs.numpy()
with torch.no_grad():
    pytorch_out = model(sample_inputs).logits.numpy()
onnx_out = session.run(None, {'pixel_values': test_input})[0]

diff = np.abs(pytorch_out - onnx_out).max()
print(f"\nValidation - Max difference: {diff:.6f}")

if diff < 1e-3:
    print("✓ Export successful - outputs match!")

    # Test with real image
    from PIL import Image
    import os
    test_images = [f for f in os.listdir() if f.lower().endswith(('.jpg', '.jpeg', '.png'))]
    if test_images:
        print(f"\n--- Testing with real image: {test_images[0]} ---")
        img = Image.open(test_images[0]).convert("RGB")
        inputs = processor(images=img, return_tensors="pt")

        # PyTorch
        with torch.no_grad():
            pytorch_real = torch.softmax(model(**inputs).logits, dim=-1)[0].numpy()

        # ONNX
        onnx_real = session.run(None, {'pixel_values': inputs['pixel_values'].numpy()})
        onnx_real_probs = torch.softmax(torch.tensor(onnx_real[0]), dim=-1)[0].numpy()

        print(f"PyTorch: safe={pytorch_real[0]:.4f}, nsfw={pytorch_real[1]:.4f}")
        print(f"ONNX:    safe={onnx_real_probs[0]:.4f}, nsfw={onnx_real_probs[1]:.4f}")
        print(f"Max diff: {np.abs(pytorch_real - onnx_real_probs).max():.6f}")
else:
    print("⚠️  WARNING: Large difference detected - export may have failed")















"""## Convert to tflite"""

import numpy as np
import ai_edge_torch
import torch

from transformers import AutoModelForImageClassification, AutoImageProcessor

# Use the mini model
model_name = "viddexa/nsfw-detection-nano"
model = AutoModelForImageClassification.from_pretrained(model_name)
processor = AutoImageProcessor.from_pretrained(model_name, use_fast=False)
model.eval()

# Get the correct input size from the processor config
input_size = processor.size.get('height', 224)  # Default to 224 if not specified
print(f"Using input size: {input_size}x{input_size}")

# Create sample inputs with the correct size
sample_inputs = (torch.randn(1, 3, input_size, input_size),)
torch_output = model(*sample_inputs)

# Convert to TFLite
print("Converting to TFLite...")
edge_model = ai_edge_torch.convert(model, sample_inputs)

# Run inference with edge model
edge_output = edge_model(*sample_inputs)

# Extract logits from both outputs
torch_logits = torch_output.logits.detach().cpu().numpy()
edge_logits = edge_output['logits']

# Compare results
print(f"\nTorch logits shape: {torch_logits.shape}")
print(f"Edge logits shape: {edge_logits.shape}")

if np.allclose(torch_logits, edge_logits, atol=1e-5):
    print("✓ Inference result with PyTorch and TFLite was within tolerance")
else:
    print("✗ Something wrong with PyTorch --> TFLite")
    print(f"Max difference: {np.max(np.abs(torch_logits - edge_logits))}")

# Export the model
output_path = 'nsfw_detector_mini.tflite'
edge_model.export(output_path)
print(f"\n✓ Model exported to: {output_path}")

# Print model info
print(f"\nModel labels: {model.config.id2label}")



"""# TFLITE ai-edge-torch"""

!pip install -r https://raw.githubusercontent.com/google-ai-edge/ai-edge-torch/main/requirements.txt
!pip install ai-edge-torch-nightly

import os
os.remove('/usr/local/lib/python3.12/dist-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so')

import ai_edge_torch
import torch
import tensorflow as tf
import numpy as np
import os
import tempfile
from transformers import AutoModelForImageClassification
from google.colab import files  # For Colab download

print("Loading model...")
model = AutoModelForImageClassification.from_pretrained("Freepik/nsfw_image_detector")
model.eval()

sample_inputs = (torch.randn(1, 3, 448, 448),)

# Create a temporary directory for SavedModel
saved_model_dir = tempfile.mkdtemp()

print(f"\nConverting to TFLite (SavedModel dir: {saved_model_dir})...")

# Convert using ai_edge_torch with SavedModel output
edge_model = ai_edge_torch.convert(
    model,
    sample_inputs,
    _saved_model_dir=saved_model_dir
)

# Save FP32 model
edge_model.export('model_fp32.tflite')
fp32_size = os.path.getsize('model_fp32.tflite') / (1024**2)
print(f"✓ FP32 TFLite size: {fp32_size:.2f} MB")

print("\nQuantizing to INT8 using TFLite converter...")

# Now load from the SavedModel directory
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.optimizations = [tf.lite.Optimize.DEFAULT]

# Representative dataset for calibration
def representative_dataset():
    for _ in range(100):
        # Generate calibration data
        data = np.random.randn(1, 3, 448, 448).astype(np.float32)
        yield [data]

converter.representative_dataset = representative_dataset

# Try full INT8 quantization
try:
    print("Attempting full INT8 quantization...")
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8

    quantized_model = converter.convert()
    output_file = 'model_int8_full.tflite'
    mode = "Full INT8"
    print("✓ Full INT8 quantization successful")

except Exception as e:
    print(f"Full INT8 failed: {e}")
    print("Falling back to hybrid quantization...")

    # Hybrid quantization (weights INT8, activations FP32)
    converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]

    quantized_model = converter.convert()
    output_file = 'model_int8_hybrid.tflite'
    mode = "Hybrid (weights INT8)"

# Save quantized model
with open(output_file, 'wb') as f:
    f.write(quantized_model)

int8_size = os.path.getsize(output_file) / (1024**2)

print(f"\n{'='*60}")
print(f"RESULTS - {mode}")
print(f"{'='*60}")
print(f"Original FP32: {fp32_size:.2f} MB")
print(f"Quantized INT8: {int8_size:.2f} MB")
print(f"Compression: {fp32_size/int8_size:.2f}x smaller")
print(f"Saved as: {output_file}")

# Download models
print(f"\n{'='*60}")
print("DOWNLOADING MODELS")
print(f"{'='*60}")

print(f"\nDownloading {output_file}...")
files.download(output_file)

print(f"\nDownloading model_fp32.tflite...")
files.download('model_fp32.tflite')

print("\n✓ All models downloaded successfully!")

# Verify quantization
print(f"\n{'='*60}")
print("VERIFICATION")
print(f"{'='*60}")

interpreter = tf.lite.Interpreter(model_path=output_file)
interpreter.allocate_tensors()

# Count quantized tensors
int8_count = 0
uint8_count = 0
fp32_count = 0

for tensor in interpreter.get_tensor_details():
    if tensor['dtype'] == np.int8:
        int8_count += 1
    elif tensor['dtype'] == np.uint8:
        uint8_count += 1
    elif tensor['dtype'] == np.float32:
        fp32_count += 1

total = len(interpreter.get_tensor_details())

print(f"Total tensors: {total}")
print(f"  INT8 tensors: {int8_count}")
print(f"  UINT8 tensors: {uint8_count}")
print(f"  FP32 tensors: {fp32_count}")

if int8_count + uint8_count > 0:
    print(f"\n✓ Model IS quantized ({int8_count + uint8_count} INT8/UINT8 tensors)")
else:
    print(f"\n✗ Model is NOT quantized")

# Test inference
print(f"\n{'='*60}")
print("TESTING INFERENCE")
print(f"{'='*60}")

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

print(f"Input shape: {input_details[0]['shape']}")
print(f"Input dtype: {input_details[0]['dtype']}")
print(f"Output shape: {output_details[0]['shape']}")
print(f"Output dtype: {output_details[0]['dtype']}")

# Test with sample input
test_input = np.random.randn(1, 3, 448, 448).astype(np.float32)

# Handle quantized input if needed
if input_details[0]['dtype'] == np.int8:
    scale, zero_point = input_details[0]['quantization']
    test_input = (test_input / scale + zero_point).astype(np.int8)
elif input_details[0]['dtype'] == np.uint8:
    scale, zero_point = input_details[0]['quantization']
    test_input = (test_input / scale + zero_point).astype(np.uint8)

interpreter.set_tensor(input_details[0]['index'], test_input)
interpreter.invoke()
output = interpreter.get_tensor(output_details[0]['index'])

print(f"✓ Inference successful")
print(f"Output shape: {output.shape}")

# Cleanup
import shutil
shutil.rmtree(saved_model_dir, ignore_errors=True)
print(f"\n✓ Cleaned up temporary files")

from google.colab import drive
drive.mount('/content/drive')





















"""# TFlite without quantization"""

import numpy as np
import ai_edge_torch
import torch
import torchvision

from transformers import AutoModelForImageClassification
import torch

model_name = "Freepik/nsfw_image_detector"
model = AutoModelForImageClassification.from_pretrained(model_name)
model.eval()

sample_inputs = (torch.randn(1, 3, 448, 448),)
torch_output = model(*sample_inputs)

edge_model = ai_edge_torch.convert(model, sample_inputs)

edge_output = edge_model(*sample_inputs)

# Extract logits from both outputs
torch_logits = torch_output.logits.detach().cpu().numpy()
edge_logits = edge_output['logits']

# Compare
if np.allclose(torch_logits, edge_logits, atol=1e-5):
    print("✓ Inference result with PyTorch and TFLite was within tolerance")
else:
    print("✗ Something wrong with PyTorch --> TFLite")

edge_model.export('nsfw_detector.tflite')

"""# TFLite with quantization"""

import numpy as np
import ai_edge_torch
import torch
from transformers import AutoModelForImageClassification
import tensorflow as tf

model_name = "Freepik/nsfw_image_detector"
model = AutoModelForImageClassification.from_pretrained(model_name)
model.eval()

sample_inputs = (torch.randn(1, 3, 448, 448),)

# Create PT2E quantizer for INT8
quant_config = ai_edge_torch.quantize.quant_config.QuantConfig(
    pt2e_quantizer=ai_edge_torch.quantize.pt2e_quantizer.PT2EQuantizer()
        .set_global(ai_edge_torch.quantize.pt2e_quantizer.get_symmetric_quantization_config(is_dynamic=False))
)

# Convert with INT8 quantization
edge_model = ai_edge_torch.convert(
    model,
    sample_inputs,
    quant_config=quant_config
)

# Test
edge_output = edge_model(*sample_inputs)
torch_output = model(*sample_inputs)

torch_logits = torch_output.logits.detach().cpu().numpy()
edge_logits = edge_output['logits']

if np.allclose(torch_logits, edge_logits, atol=0.1):
    print("✓ INT8 quantized model within tolerance")
else:
    print("✗ Check quantization accuracy")

edge_model.export('nsfw_detector_int8.tflite')

# Verify INT8 quantization with ai_edge_litert
print("\n=== Quantization Verification ===")
try:
    from ai_edge_litert.interpreter import Interpreter
    interpreter = Interpreter(model_path='nsfw_detector_int8.tflite')
    interpreter.allocate_tensors()
    print("✓ Using ai_edge_litert")
except ImportError:
    print("Install ai_edge_litert: pip install ai-edge-litert")
    interpreter = None

if interpreter:
    int8_count = 0
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    print(f"Input dtype: {input_details[0]['dtype']}")
    print(f"Output dtype: {output_details[0]['dtype']}")

    # Check model size
    import os
    size_mb = os.path.getsize('nsfw_detector_int8.tflite') / (1024 * 1024)
    print(f"Model size: {size_mb:.2f} MB")

# Inference code for quantized model
print("\n=== Running Inference ===")
from PIL import Image

image = Image.open("test_image.jpg").convert('RGB')
image = image.resize((448, 448), Image.BICUBIC)

img_array = np.array(image, dtype=np.float32) / 255.0

mean = np.array([0.485, 0.456, 0.406], dtype=np.float32)
std = np.array([0.229, 0.224, 0.225], dtype=np.float32)
img_array = (img_array - mean) / std

if input_details[0]['shape'][1] == 3:
    img_array = np.transpose(img_array, (2, 0, 1))
    img_array = np.expand_dims(img_array, axis=0)
else:
    img_array = np.expand_dims(img_array, axis=0)

interpreter.set_tensor(input_details[0]['index'], img_array)
interpreter.invoke()

output = interpreter.get_tensor(output_details[0]['index'])
logits = output[0]

probs = np.exp(logits - np.max(logits))
probs = probs / np.sum(probs)

labels = ['neutral', 'low', 'medium', 'high']
predicted_class = np.argmax(probs)

print(f"\nPrediction: {labels[predicted_class]}")
print(f"Confidence: {probs[predicted_class]:.2%}")
print(f"\nAll probabilities:")
for label, prob in zip(labels, probs):
    print(f"  {label:8s}: {prob:.4f} ({prob*100:.2f}%)")



import numpy as np
import ai_edge_torch
import torch
import torchvision
import torch.nn as nn
from transformers import AutoModelForImageClassification
import torch

model_name = "Freepik/nsfw_image_detector"
model = AutoModelForImageClassification.from_pretrained(model_name)
model.eval()

# 2. Apply dynamic quantization
# This single line performs the conversion for specified layers
quantized_model = torch.quantization.quantize_dynamic(
    model,                                    # The model to quantize
    {nn.Linear},                                   # The types of layers to quantize (here, only Linear)
    dtype=torch.qint8                              # The target data type (signed 8-bit integer)
)

# The 'quantized_model' can now be used for inference
# The weights are stored as INT8 internally, saving memory
print("Original model size (FP32):")
print(sum(p.numel() * p.element_size() for p in model.parameters()) / (1024**2), "MB")

print("\nQuantized model size (INT8):")
print(sum(p.numel() * p.element_size() for p in quantized_model.parameters()) / (1024**2), "MB")

"""# Prediction"""

"""Simple TFLite NSFW detector inference"""

import numpy as np
from PIL import Image

# Load model (try ai_edge_litert first, fallback to tensorflow)
try:
    from ai_edge_litert.interpreter import Interpreter
except ImportError:
    from tensorflow.lite import Interpreter

interpreter = Interpreter(model_path="model_int8_full.tflite")
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Load and preprocess image
for file in [i for i in os.listdir() if '.jpg' in i]:
  image = Image.open(file).convert('RGB').resize((448, 448))
  img_array = np.array(image, dtype=np.float32) / 255.0

  # ImageNet normalization
  mean = np.array([0.485, 0.456, 0.406], dtype=np.float32)
  std = np.array([0.229, 0.224, 0.225], dtype=np.float32)
  img_array = (img_array - mean) / std

  # Convert to channels-first if needed
  if input_details[0]['shape'][1] == 3:
      img_array = np.transpose(img_array, (2, 0, 1))
  img_array = np.expand_dims(img_array, axis=0)

  # Run inference
  interpreter.set_tensor(input_details[0]['index'], img_array)
  interpreter.invoke()
  output = interpreter.get_tensor(output_details[0]['index'])

  # Get probabilities
  logits = output[0]
  probs = np.exp(logits - np.max(logits))
  probs = probs / np.sum(probs)

  # Print results
  labels = ['neutral', 'low', 'medium', 'high']
  predicted_class = np.argmax(probs)

  print(f"\nPrediction: {file} {labels[predicted_class]} ({probs[predicted_class]:.1%})")
  print("\nProbabilities:")
  for label, prob in zip(labels, probs):
      print(f"  {label}: {prob:.1%}")

"""Simple TFLite NSFW detector inference"""

import numpy as np
from PIL import Image
import os

# Load model
try:
    from ai_edge_litert.interpreter import Interpreter
except ImportError:
    from tensorflow.lite import Interpreter

interpreter = Interpreter(model_path="model_int8_full.tflite")
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

print(f"Input shape: {input_details[0]['shape']}")
print(f"Input dtype: {input_details[0]['dtype']}")
print(f"Input quantization: {input_details[0]['quantization']}")
print(f"Output quantization: {output_details[0]['quantization']}")

# Load and preprocess image
for file in [i for i in os.listdir() if '.jpg' in i]:
    image = Image.open(file).convert('RGB').resize((448, 448))

    # NO preprocessing - just raw pixels scaled to match training
    # The quantization was calibrated on random normal data, not ImageNet-normalized data
    img_array = np.array(image, dtype=np.float32)

    # Scale from [0, 255] to approximately [-1, 1] to match torch.randn distribution
    img_array = (img_array - 127.5) / 127.5

    # Convert to channels-first (C, H, W)
    img_array = np.transpose(img_array, (2, 0, 1))
    img_array = np.expand_dims(img_array, axis=0)

    # Quantize to INT8
    img_array_int8 = np.round(img_array * 127).clip(-128, 127).astype(np.int8)

    # Run inference
    interpreter.set_tensor(input_details[0]['index'], img_array_int8)
    interpreter.invoke()
    output = interpreter.get_tensor(output_details[0]['index'])

    # Dequantize output
    if output.dtype == np.int8:
        output = output.astype(np.float32) / 127.0

    # Get probabilities
    logits = output[0]
    probs = np.exp(logits - np.max(logits))
    probs = probs / np.sum(probs)

    # Print results
    labels = ['neutral', 'low', 'medium', 'high']
    predicted_class = np.argmax(probs)

    print(f"\n{file}")
    print(f"Prediction: {labels[predicted_class]} ({probs[predicted_class]:.1%})")
    print("Probabilities: " + " | ".join([f"{label}: {prob:.1%}" for label, prob in zip(labels, probs)]))

"""
Simple TFLite inference for NSFW detector
Fixed for ai-edge-torch converted models
"""

import numpy as np
from PIL import Image

# ============================================================================
# METHOD 1: Use ai_edge_litert (Recommended - matches ai-edge-torch)
# ============================================================================
try:
    from ai_edge_litert.interpreter import Interpreter

    # Load the TFLite model
    interpreter = Interpreter(model_path="nsfw_detector.tflite")
    interpreter.allocate_tensors()

    # Get input and output details
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    print("✓ Loaded with ai_edge_litert")

except ImportError:
    print("ai_edge_litert not found, install with: pip install ai-edge-litert")
    print("Trying tensorflow.lite...")

    # Fallback to tensorflow.lite with error handling
    import tensorflow as tf

    try:
        interpreter = tf.lite.Interpreter(model_path="nsfw_detector.tflite")
        interpreter.allocate_tensors()
        input_details = interpreter.get_input_details()
        output_details = interpreter.get_output_details()
        print("✓ Loaded with tensorflow.lite")
    except Exception as e:
        print(f"✗ Failed to load model: {e}")
        print("\nSolution: Install ai_edge_litert")
        print("  pip install ai-edge-litert")
        exit(1)

# Print model info
print(f"\nInput shape: {input_details[0]['shape']}")
print(f"Output shape: {output_details[0]['shape']}")

# Load and preprocess the image
image = Image.open("test_image_nsfw_high.jpg").convert('RGB')
image = image.resize((448, 448), Image.BICUBIC)

# Convert to numpy array and normalize to [0, 1]
img_array = np.array(image, dtype=np.float32) / 255.0

# Apply ImageNet normalization (EVA02 standard)
mean = np.array([0.485, 0.456, 0.406], dtype=np.float32)
std = np.array([0.229, 0.224, 0.225], dtype=np.float32)
img_array = (img_array - mean) / std

# Check if model expects channels-first (N, C, H, W) or channels-last (N, H, W, C)
input_shape = input_details[0]['shape']
if input_shape[1] == 3:  # Channels first (1, 3, 448, 448)
    img_array = np.transpose(img_array, (2, 0, 1))  # HWC -> CHW
    img_array = np.expand_dims(img_array, axis=0)  # Add batch dimension
else:  # Channels last (1, 448, 448, 3)
    img_array = np.expand_dims(img_array, axis=0)  # Add batch dimension

print(f"Preprocessed image shape: {img_array.shape}")

# Set the input tensor
interpreter.set_tensor(input_details[0]['index'], img_array)

# Run inference
interpreter.invoke()

# Get the output
output = interpreter.get_tensor(output_details[0]['index'])
logits = output[0]

# Apply softmax to get probabilities
probs = np.exp(logits - np.max(logits))  # Subtract max for numerical stability
probs = probs / np.sum(probs)

# Get prediction
labels = ['neutral', 'low', 'medium', 'high']
predicted_class = np.argmax(probs)

print(f"\n{'='*50}")
print(f"Prediction: {labels[predicted_class]}")
print(f"Confidence: {probs[predicted_class]:.2%}")
print(f"\nAll probabilities:")
for label, prob in zip(labels, probs):
    print(f"  {label:8s}: {prob:.4f} ({prob*100:.2f}%)")
print(f"{'='*50}")

# Calculate cumulative probabilities (Freepik method)
print(f"\nCumulative probabilities (NSFW detection):")
cum_probs = {}
danger_sum = 0.0
for i in range(len(probs) - 1, -1, -1):
    danger_sum += probs[i]
    if i == 0:  # neutral
        danger_sum = probs[i]
    cum_probs[labels[i]] = danger_sum
    print(f"  {labels[i]:8s}: {danger_sum:.4f} ({danger_sum*100:.2f}%)")

# Check NSFW at different levels
print(f"\nNSFW Detection (threshold: 0.5):")
for level in ['low', 'medium', 'high']:
    is_nsfw = cum_probs[level] >= 0.5
    print(f"  {level:8s}: {is_nsfw}")









"""# ONNX"""

! pip install onnxscript onnxruntime

"""
Simple ONNX inference for NSFW detector
Matches preprocessing and output format from TFLite reference
"""

import onnxruntime as ort
import numpy as np
from PIL import Image

try:
    # Load ONNX model
    print("Loading ONNX model...")
    session = ort.InferenceSession("nsfw_detector.onnx")

    # Get input and output details
    input_details = session.get_inputs()[0]
    output_details = session.get_outputs()[0]

    print("✓ Loaded ONNX model successfully")
    print(f"\nInput name: {input_details.name}")
    print(f"Input shape: {input_details.shape}")
    print(f"Output name: {output_details.name}")
    print(f"Output shape: {output_details.shape}")

    # Load and preprocess the image
    image_path = "test_image.jpg"
    image = Image.open(image_path).convert('RGB')
    image = image.resize((448, 448), Image.BICUBIC)

    # Convert to numpy array and normalize to [0, 1]
    img_array = np.array(image, dtype=np.float32) / 255.0

    # Apply ImageNet normalization (EVA02 standard)
    mean = np.array([0.485, 0.456, 0.406], dtype=np.float32)
    std = np.array([0.229, 0.224, 0.225], dtype=np.float32)
    img_array = (img_array - mean) / std

    # Convert to channels-first format (N, C, H, W)
    img_array = np.transpose(img_array, (2, 0, 1))  # HWC -> CHW
    img_array = np.expand_dims(img_array, axis=0)  # Add batch dimension

    print(f"Preprocessed image shape: {img_array.shape}")

    # Run inference
    outputs = session.run([output_details.name], {input_details.name: img_array})
    logits = outputs[0][0]

    # Apply softmax to get probabilities
    probs = np.exp(logits - np.max(logits))  # Subtract max for numerical stability
    probs = probs / np.sum(probs)

    # Get prediction
    labels = ['normal', 'nsfw']
    predicted_class = np.argmax(probs)

    print(f"\n{'='*50}")
    print(f"Prediction: {labels[predicted_class]}")
    print(f"Confidence: {probs[predicted_class]:.2%}")
    print(f"\nAll probabilities:")
    for label, prob in zip(labels, probs):
        print(f"  {label:8s}: {prob:.4f} ({prob*100:.2f}%)")
    print(f"{'='*50}")

    # Additional output (matching TFLite style)
    print(f"\nRaw logits: {logits}")
    print(f"Softmax probabilities: {probs}")

    # NSFW Detection (threshold: 0.5)
    print(f"\nNSFW Detection (threshold: 0.5):")
    is_nsfw = probs[1] >= 0.5
    print(f"  Is NSFW: {is_nsfw}")
    print(f"  NSFW probability: {probs[1]:.4f} ({probs[1]*100:.2f}%)")

except FileNotFoundError:
    print(f"✗ Error: Could not find image file '{image_path}'")
    print("Please ensure the image exists in the current directory")
except Exception as e:
    print(f"✗ Error during inference: {e}")
    import traceback
    traceback.print_exc()

from transformers import ViTForImageClassification, ViTImageProcessor
import torch

model_name = "Falconsai/nsfw_image_detection"
model = ViTForImageClassification.from_pretrained(model_name)
processor = ViTImageProcessor.from_pretrained(model_name)
model.eval()
dummy_input = torch.randn(1, 3, 224, 224)
torch.onnx.export(
    model,
    dummy_input,
    "nsfw_detection.onnx",
    input_names=['pixel_values'],
    output_names=['logits'],
    dynamic_axes={
        'pixel_values': {0: 'batch_size'},
        'logits': {0: 'batch_size'}
    },
    opset_version=14
)

import onnxruntime as ort
import numpy as np
from PIL import Image
from transformers import ViTImageProcessor

# Load ONNX model
session = ort.InferenceSession("nsfw_detection.onnx")

# Load the processor to preprocess images
processor = ViTImageProcessor.from_pretrained('Falconsai/nsfw_image_detection')

# Define label mapping (from the model's config)
id2label = {0: 'normal', 1: 'nsfw'}

# Prepare input
image = Image.open("non_nsfw_image_2.jpg")
inputs = processor(images=image, return_tensors="np")

# Run inference
outputs = session.run(None, {"pixel_values": inputs['pixel_values']})
logits = outputs[0]

# Get predicted label
predicted_label_id = np.argmax(logits, axis=-1).item()
predicted_label = id2label[predicted_label_id]

print(f"Predicted label: {predicted_label}")
print(f"Confidence scores: normal={logits[0][0]:.4f}, nsfw={logits[0][1]:.4f}")

!pip install -q transformers torch coremltools pillow

import torch
import coremltools as ct
from transformers import AutoModelForImageClassification
import torch.nn as nn

class LogitsOnlyWrapper(nn.Module):
    """Wrapper that extracts only logits from HuggingFace model output"""
    def __init__(self, hf_model):
        super().__init__()
        self.model = hf_model

    def forward(self, pixel_values):
        output = self.model(pixel_values)
        return output.logits

def convert_nsfw_model():
    try:
        print("📥 Loading model from Hugging Face...")
        hf_model = AutoModelForImageClassification.from_pretrained(
            "Falconsai/nsfw_image_detection"
        )

        # Wrap model to return only logits
        wrapped_model = LogitsOnlyWrapper(hf_model)
        wrapped_model.eval()

        print("✅ Model loaded successfully")
        print(f"   Classes: {hf_model.config.id2label}")

        # Create example input
        example_input = torch.rand(1, 3, 224, 224)

        print("\n🔄 Tracing model...")
        with torch.no_grad():
            traced_model = torch.jit.trace(wrapped_model, example_input)

        print("✅ Model traced successfully")

        # Convert to Core ML (iOS 15+)
        print("\n📦 Converting to Core ML mlprogram...")
        coreml_model = ct.convert(
            traced_model,
            inputs=[ct.TensorType(name="image", shape=(1, 3, 224, 224))],
            outputs=[ct.TensorType(name="logits")],
            convert_to="mlprogram",
            minimum_deployment_target=ct.target.iOS15
        )

        # Add metadata
        coreml_model.author = "Falconsai"
        coreml_model.short_description = "NSFW Image Classification"
        coreml_model.version = "1.0"
        coreml_model.user_defined_metadata['classes'] = "normal,nsfw"

        # Save
        coreml_model.save("nsfw_detection.mlpackage")
        print("✅ Saved: nsfw_detection.mlpackage")

        # Convert to legacy format with higher iOS target
        print("\n📦 Converting to legacy .mlmodel format...")
        try:
            coreml_legacy = ct.convert(
                traced_model,
                inputs=[ct.TensorType(name="image", shape=(1, 3, 224, 224))],
                minimum_deployment_target=ct.target.iOS14  # Changed from iOS13 to iOS14
            )

            coreml_legacy.user_defined_metadata['classes'] = "normal,nsfw"
            coreml_legacy.save("nsfw_detection.mlmodel")
            print("✅ Saved: nsfw_detection.mlmodel (iOS 14+)")
        except ValueError as e:
            print(f"⚠️  Legacy format conversion failed: {e}")
            print("   Using iOS 15+ target instead...")

            # Try with iOS15 as minimum for legacy
            coreml_legacy = ct.convert(
                traced_model,
                inputs=[ct.TensorType(name="image", shape=(1, 3, 224, 224))],
                minimum_deployment_target=ct.target.iOS15
            )

            coreml_legacy.user_defined_metadata['classes'] = "normal,nsfw"
            coreml_legacy.save("nsfw_detection_ios15.mlmodel")
            print("✅ Saved: nsfw_detection_ios15.mlmodel (iOS 15+)")

        print("\n✨ Conversion complete! You now have:")
        print("   • nsfw_detection.mlpackage (iOS 15+, recommended)")

    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()

# Run the conversion
convert_nsfw_model()



"""
PyTorch to TFLite Conversion Script for NSFW Detection Model
This script converts the Hugging Face PyTorch model to TFLite format with verification.
"""

import os
import torch
import numpy as np
import ai_edge_torch
from transformers import AutoImageProcessor, AutoModelForImageClassification
from PIL import Image


def convert_to_tflite(
    model_path: str = "./nsfw-image-detection-384",
    output_path: str = "./nsfw-image-detection-384.tflite",
    test_image_path: str = "./test_images/normal_1.jpg"
):
    """
    Convert a Hugging Face PyTorch model to TFLite format.

    Args:
        model_path: Path to the saved PyTorch model or model name from Hugging Face
        output_path: Path where TFLite model will be saved
        test_image_path: Path to test image for verification
    """

    print("=" * 80)
    print("PyTorch to TFLite Conversion")
    print("=" * 80)

    # Step 1: Load the model and processor
    print("\n[1/5] Loading PyTorch model and processor...")
    processor = AutoImageProcessor.from_pretrained(model_path, use_fast=False)
    model = AutoModelForImageClassification.from_pretrained(model_path)
    model.eval()
    print("✓ Model loaded successfully")

    # Step 2: Create sample input for conversion
    print("\n[2/5] Creating sample input tensor...")
    input_size = 384
    batch_size = 1
    channels = 3

    sample_inputs = (torch.randn(batch_size, channels, input_size, input_size),)
    print(f"✓ Sample input shape: {sample_inputs[0].shape}")

    # Step 3: Get PyTorch baseline output
    print("\n[3/5] Getting PyTorch baseline output...")
    with torch.no_grad():
        pytorch_output = model(*sample_inputs)
        pytorch_logits = pytorch_output.logits.detach().cpu().numpy()
    print("✓ PyTorch inference complete")

    # Step 4: Convert to TFLite
    print("\n[4/5] Converting model to TFLite format...")
    try:
        edge_model = ai_edge_torch.convert(model, sample_inputs)
        print("✓ Model converted to TFLite successfully")
    except Exception as e:
        print(f"✗ Conversion failed: {e}")
        raise

    # Step 5: Verify TFLite model
    print("\n[5/5] Verifying TFLite model...")

    # Test with sample input
    edge_output = edge_model(*sample_inputs)
    edge_logits = edge_output['logits']

    # Compare outputs
    max_diff = np.max(np.abs(pytorch_logits - edge_logits))
    print(f"✓ TFLite inference successful")
    print(f"  Max difference between PyTorch and TFLite: {max_diff:.6f}")

    if np.allclose(pytorch_logits, edge_logits, atol=1e-5):
        print("  ✓ Inference result with PyTorch and TFLite was within tolerance")
    elif np.allclose(pytorch_logits, edge_logits, atol=1e-3):
        print("  ✓ Outputs are very close (acceptable difference)")
    else:
        print("  ⚠ Warning: Outputs differ significantly")
        print("  ✗ Something wrong with PyTorch --> TFLite")

    # Test with actual image if available
    if os.path.exists(test_image_path):
        print("\nTesting with real image...")
        test_image = Image.open(test_image_path).convert("RGB")

        # Prepare input
        inputs = processor(images=test_image, return_tensors="pt")
        pixel_values = inputs['pixel_values']

        # PyTorch inference
        with torch.no_grad():
            pytorch_output = model(**inputs).logits
            pytorch_probs = torch.softmax(pytorch_output, dim=-1)[0].numpy()

        # TFLite inference
        edge_output = edge_model(pixel_values)
        edge_logits = edge_output['logits']
        edge_probs = torch.softmax(torch.tensor(edge_logits), dim=-1)[0].numpy()

        # Compare
        max_diff = np.max(np.abs(pytorch_probs - edge_probs))
        print(f"  Max difference on real image: {max_diff:.6f}")

        # Display predictions
        print("\nPrediction Comparison:")
        print("-" * 60)
        for i in range(len(pytorch_probs)):
            label = model.config.id2label[i]
            print(f"{label:10} | PyTorch: {pytorch_probs[i]:.4f} | TFLite: {edge_probs[i]:.4f}")
    else:
        print(f"\n⚠ Test image not found at {test_image_path}, skipping real image comparison")

    # Export TFLite model
    print(f"\nExporting TFLite model to: {output_path}")
    edge_model.export(output_path)
    print("✓ Model exported successfully")

    # Summary
    print("\n" + "=" * 80)
    print("Conversion Complete!")
    print("=" * 80)
    print(f"\nTFLite model saved at: {output_path}")
    if os.path.exists(output_path):
        print(f"Model size: {os.path.getsize(output_path) / (1024*1024):.2f} MB")

    return output_path

convert_to_tflite(
        model_path="Marqo/nsfw-image-detection-384",
        output_path="./nsfw_detector.tflite",
        test_image_path="./normal_1.jpg"
    )

